development:
  adapter: postgresql
  encoding: unicode
  database: frst_development 
  pool: 5
  username: alen909
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: frst_test
  pool: 5
  username: alen909
  password:
